stages:
- build

build_job:
    stage: build
    tags: 
    - simol-osx10-clang
    script:
    - mv cmake/config/config-ci.cmake cmake/config/config.cmake
    - mkdir -p build
    - cd build
    - cmake ..
    - make

