stages:
- build

build_job:
    stage: build
    tags: simol-osx10-clang
    script:
    - mkdir -p build
    - cd build 
    - cmake -D SIMOL_AUTO_INSTALL=true -D SIMOL_EXTERNAL_DIR=/Users/ci/external ..
    - make

