if(EXISTS ${BOOST_INSTALL_DIR})
  message(STATUS "Boost is declared to be installed in ${BOOST_INSTALL_DIR}")
else()
  if(ENABLE_DOWNLOAD)
    set(LIBRARIES_TO_DOWNLOAD ${LIBRARIES_TO_DOWNLOAD} BOOST)
    set(BOOST_URL http://sourceforge.net/projects/boost/files/boost/1.57.0/boost_1_57_0.tar.gz)
    set(BOOST_URL_MD5 4d0d77e06fef87b4fcd2c9b72cc8dc55)
    set(BOOST_CONFIGURE_COMMAND ./bootstrap.sh)
    set(BOOST_BUILD_COMMAND ./b2 install --prefix=<INSTALL_DIR>)
    set(BOOST_ARGS -D CMAKE_INSTALL_PREFIX=<INSTALL_DIR>)
  else(ENABLE_DOWNLOAD)
    message(FATAL_ERROR "Boost not found. Please provide a value to BOOST_DIR or set ENABLE_DOWNLOAD to True")
  endif()
endif()

